apiVersion: v1
kind: ConfigMap
metadata:
  name: ${option.APP}-website
data:
  index.html: |
    <html>
    <h1>Les grandes perches (et la oompa loompa)</h1>
    <body>
    Vous ne croirez jamais ce que se cache derriere ce lien ! Decouvrez le contenu le plus etonnant de tous les temps ! <br />
    <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Cliquez ici !</a>
    </body>
    </html>