${option.APP}apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${option.APP}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${option.APP}
  template:
    metadata:
      labels:
        app: ${option.APP}
    spec:
      containers:
        - name: ${option.APP}
          image: ${option.APP}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ${option.APP}-website-volume
              mountPath: /usr/share/${option.APP}/html
              readOnly: true
      volumes:
        - name: ${option.APP}-website-volume
          configMap:
            name: ${option.APP}-website
