apiVersion: v1
kind: Service
metadata:
  name: ${option.APP}-service-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.0.51  # Adresse IP statique souhaitée
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ${option.APP}
