apiVersion: v1
kind: Service
metadata:
  name: ${option.APP}-service
  labels:
    app: ${option.APP}
spec:
  selector:
    app: ${option.APP}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: ${option.APP}-service-lb
spec:
  type: LoadBalancer
  selector:
    app: ${option.APP}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80