# deploy step
variables:
  KUBE_CONTEXT: elite/k8s-connection:k8s-connection

stages:
  - deploy

deploy-configmap:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl apply -f $CI_PROJECT_DIR/configmap.yaml
  